# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_connector: ['pagerduty', 'twitter_v2', 'circleci', 'firecracker', 'quickbase',
                           'apache_pulsar_functions', 'aquarius', 'provider', 'blackboard', 'docusign_esignature',
                           'docusign_click', 'docusign_rooms', 'xero_assets', 'xero_files', 'xero_projects',
                           'xero_payroll_nz', 'xero_payroll_uk', 'ably_control', 'ebay', 'interzoid', 'google_drive',
                           'google_analytics_v3', 'google_healthcare', 'google_calendar', 'google_compute_engine',
                           'google_cloud_asset', 'google_cloud_dns', 'google_cloud_scheduler', 'google_people',
                           'google_admob', 'google_android_management', 'google_app_engine_admin',
                           'google_artifact_registry', 'google_cloud_build', 'google_classroom', 'google_cloud_tasks',
                           'google_data_fusion', 'google_data_pipelines', 'google_language', "google_apps_script",
                           "google_cloud_logging", "google_cloud_monitoring", "google_translate", "google_cloud_shell",
                           "google_sheets", 'guru', 'vonage_messages', 'vonage_dispatch', 'amazon_kinesis',
                           'amazon_kinesis_analytics', 'amazon_kinesis_firehose', "amazon_chime", "amazon_cloudwatch",
                           "amazon_dynamodb", "aws_amplify", "aws_amplify_backend", "amazon_aurora"
        ]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install -Dtarget_connector=${{ matrix.target_connector }}

    - name: Stage artifacts for upload
      run: >
        mkdir -p staging/${{ matrix.target_connector }} &&
        cp target/*car.zip staging/${{ matrix.target_connector }}/${{ matrix.target_connector }}-car.zip &&
        cp target/connector-descriptor* staging/${{ matrix.target_connector }}/${{ matrix.target_connector }}.xml
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target_connector }}
        path: staging/${{ matrix.target_connector }}/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: staging/

    - name: Stage artifact README.md
      run: cp $GITHUB_WORKSPACE/README.md staging/README.md

    - name: Stage openapi document
      run: cp $GITHUB_WORKSPACE/src/main/resources/"OpenAPI Connector Factory.docx" staging/"OpenAPI Connector Factory.docx"

    - name: Stage connector specifications
      run: for connector in $GITHUB_WORKSPACE/src/main/resources/*; do cp "$connector"/*.{json,yaml} staging/$(basename "$connector") 2> /dev/null || :; done

    - name: Stage connector readme
      run: for connector in $GITHUB_WORKSPACE/src/main/resources/*; do cp "$connector"/*.md staging/$(basename "$connector") 2> /dev/null || :; done

    - name: Push build artifacts to artifact repository
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'staging'
        destination-github-username: 'Enspire-Tech'
        destination-repository-name: 'openapi-connector-artifacts'
        user-email: jacob.mortelliti@enspire-tech.com
        target-branch: master