# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_connector: ['pagerduty']
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install -Dtarget_connector=${{ matrix.target_connector }}

    - name: Stage artifacts for upload
      run: >
        mkdir -p staging/${{ matrix.target_connector }} &&
        cp target/*car.zip staging/${{ matrix.target_connector }}/${{ matrix.target_connector }}-car.zip &&
        cp target/connector-descriptor* staging/${{ matrix.target_connector }}/${{ matrix.target_connector }}.xml
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.target_connector }}
        path: staging/${{ matrix.target_connector }}/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: staging/

    - name: Write README.md
      run: echo "# openapi-connector-artifacts" > staging/README.md

    - name: Push build artifacts to artifact repository
      uses: cpina/github-action-push-to-another-repository@v1.3
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'staging'
        destination-github-username: 'Enspire-Tech'
        destination-repository-name: 'openapi-connector-artifacts'
        user-email: jacob.mortelliti@enspire-tech.com
        target-branch: master